apiVersion: v1
kind: Pod
metadata:
 annotations:
   k8s.v1.cni.cncf.io/networks: '[
     {
      "name": "eric-pc-up-data-plane-net1",
      "namespace": "pcg"
     },
     {
      "name": "eric-pc-up-data-plane-net2",
      "namespace": "pcg"
     }
   ]'
   cpu-load-balancing.crio.io: disable
   cpu-quota.crio.io: disable
   irq-load-balancing.crio.io: "disable"
 labels:
   app: pktgen
 name: pktgen
 namespace: pcg
spec:
  tolerations:
   - key: "high-throughput"
     value: "true"
     effect: "NoSchedule"
  containers:
    - command:
        - /bin/bash
        - -c
        - sleep infinity
      # image: quay.io/javierpena/dpdk:21.11.2_c9s
      image:  quay.io/dchavero/pktgen:latest
      imagePullPolicy: Always
      name: pktgen
      resources:
        limits:
          cpu: "10"
          hugepages-1Gi: 4Gi
          memory: 2Gi
        requests:
          cpu: "10"
          hugepages-1Gi: 4Gi
          memory: 2Gi
      securityContext:
        privileged: true
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
      volumeMounts:
        - mountPath: /mnt/huge
          name: hugepages
        - name: modules
          mountPath: /lib/modules
  terminationGracePeriodSeconds: 5
  nodeSelector:
    kubernetes.io/hostname: htworker2.ocp1.e5gc.bos2.lab
  volumes:
    - name: modules
      hostPath:
        path: /lib/modules
    - emptyDir:
        medium: HugePages
      name: hugepages
  runtimeClassName: performance-ht100gb

